"""phase 1: projects, observations, milestones, events, data quality, validation cohort

Revision ID: baa5379b786f
Revises: 
Create Date: 2026-09-04 12:04:38.793469

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baa5379b786f'
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_quality_issues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('issue_type', sa.Text(), nullable=False),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('table_name', sa.Text(), nullable=False),
    sa.Column('record_id', sa.Text(), nullable=False),
    sa.Column('field', sa.Text(), nullable=True),
    sa.Column('original_value', sa.Text(), nullable=True),
    sa.Column('corrected_value', sa.Text(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('source_file', sa.Text(), nullable=True),
    sa.Column('source_row', sa.Integer(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('project_name', sa.Text(), nullable=False),
    sa.Column('agency', sa.Text(), nullable=True),
    sa.Column('agency_code', sa.String(length=64), nullable=True),
    sa.Column('ministry', sa.String(length=255), nullable=True),
    sa.Column('sector', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=128), nullable=True),
    sa.Column('original_cost_crore', sa.Numeric(precision=14, scale=2, asdecimal=False), nullable=True),
    sa.Column('revised_cost_crore', sa.Numeric(precision=14, scale=2, asdecimal=False), nullable=True),
    sa.Column('date_of_approval', sa.Date(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('original_completion_date', sa.Date(), nullable=True),
    sa.Column('revised_completion_date', sa.Date(), nullable=True),
    sa.Column('current_status', sa.String(length=64), nullable=True),
    sa.Column('first_observation_month', sa.Date(), nullable=True),
    sa.Column('latest_observation_month', sa.Date(), nullable=True),
    sa.Column('observation_count', sa.Integer(), nullable=False),
    sa.Column('source_files', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('raw_observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_file', sa.Text(), nullable=False),
    sa.Column('source_row', sa.Integer(), nullable=False),
    sa.Column('raw_json', sa.Text(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('event_month', sa.Date(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('previous_value', sa.String(length=255), nullable=True),
    sa.Column('new_value', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_milestones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('milestone_name', sa.Text(), nullable=False),
    sa.Column('planned_date', sa.Date(), nullable=True),
    sa.Column('actual_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('source_file', sa.String(length=255), nullable=True),
    sa.Column('source_row', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_monthly_observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('observation_month', sa.Date(), nullable=False),
    sa.Column('report_label', sa.String(length=32), nullable=False),
    sa.Column('record_type', sa.String(length=64), nullable=True),
    sa.Column('date_of_approval', sa.Date(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('target_completion_date', sa.Date(), nullable=True),
    sa.Column('revised_completion_date', sa.Date(), nullable=True),
    sa.Column('original_cost_crore', sa.Numeric(precision=14, scale=2, asdecimal=False), nullable=True),
    sa.Column('revised_cost_crore', sa.Numeric(precision=14, scale=2, asdecimal=False), nullable=True),
    sa.Column('cumulative_expenditure_crore', sa.Numeric(precision=14, scale=2, asdecimal=False), nullable=True),
    sa.Column('physical_progress_percent', sa.Numeric(precision=6, scale=2, asdecimal=False), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source_file', sa.String(length=255), nullable=False),
    sa.Column('source_row', sa.Integer(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'observation_month', name='uq_project_observation_month')
    )
    op.create_table('validation_cohort',
    sa.Column('cohort_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('reason_selected', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('cohort_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('validation_cohort')
    op.drop_table('project_monthly_observations')
    op.drop_table('project_milestones')
    op.drop_table('project_events')
    op.drop_table('raw_observations')
    op.drop_table('projects')
    op.drop_table('data_quality_issues')
    # ### end Alembic commands ###
