"""phase 8: web_evidence table

Revision ID: dcc75cd997cc
Revises: 5e2b9c7c7644
Create Date: 2026-09-04 22:32:52.368445

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcc75cd997cc'
down_revision: str | None = '5e2b9c7c7644'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('web_evidence',
    sa.Column('evidence_id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('source_type', sa.String(length=16), nullable=False),
    sa.Column('topic', sa.String(length=64), nullable=False),
    sa.Column('query_used', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('published_date', sa.Date(), nullable=True),
    sa.Column('date_confidence', sa.String(length=16), nullable=False),
    sa.Column('finding', sa.Text(), nullable=False),
    sa.Column('project_relevance', sa.Float(), nullable=False),
    sa.Column('trust_tier', sa.String(length=8), nullable=False),
    sa.Column('source_quality', sa.String(length=16), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('evidence_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('web_evidence')
    # ### end Alembic commands ###
