"""phase 2: feature store (feature_versions, project_monthly_features)

Revision ID: fa55f75c6aaa
Revises: baa5379b786f
Create Date: 2026-09-04 12:19:34.391683

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa55f75c6aaa'
down_revision: str | None = 'baa5379b786f'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_versions',
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('rolling_window_months', sa.Integer(), nullable=False),
    sa.Column('expected_progress_method', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('version')
    )
    op.create_table('project_monthly_features',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('snapshot_month', sa.Date(), nullable=False),
    sa.Column('feature_version', sa.String(length=32), nullable=False),
    sa.Column('cost_utilisation', sa.Numeric(precision=10, scale=6, asdecimal=False), nullable=True),
    sa.Column('expenditure_growth', sa.Numeric(precision=10, scale=6, asdecimal=False), nullable=True),
    sa.Column('monthly_expenditure_growth', sa.Numeric(precision=14, scale=4, asdecimal=False), nullable=True),
    sa.Column('schedule_utilisation', sa.Numeric(precision=10, scale=6, asdecimal=False), nullable=True),
    sa.Column('physical_progress', sa.Numeric(precision=6, scale=2, asdecimal=False), nullable=True),
    sa.Column('expected_progress', sa.Numeric(precision=10, scale=4, asdecimal=False), nullable=True),
    sa.Column('progress_gap', sa.Numeric(precision=10, scale=4, asdecimal=False), nullable=True),
    sa.Column('expenditure_progress_divergence', sa.Numeric(precision=10, scale=6, asdecimal=False), nullable=True),
    sa.Column('monthly_progress_change', sa.Numeric(precision=10, scale=4, asdecimal=False), nullable=True),
    sa.Column('rolling_progress_change', sa.Numeric(precision=10, scale=4, asdecimal=False), nullable=True),
    sa.Column('rolling_expenditure_change', sa.Numeric(precision=14, scale=4, asdecimal=False), nullable=True),
    sa.Column('project_age_months', sa.Integer(), nullable=True),
    sa.Column('remaining_schedule_months', sa.Integer(), nullable=True),
    sa.Column('remaining_cost_budget_crore', sa.Numeric(precision=14, scale=4, asdecimal=False), nullable=True),
    sa.Column('input_observation_count', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['feature_version'], ['feature_versions.version'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'snapshot_month', 'feature_version', name='uq_project_snapshot_feature_version')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_monthly_features')
    op.drop_table('feature_versions')
    # ### end Alembic commands ###
